name: "Autobackup"
description: "Autobackup add-on"
version: "latest"
slug: "autobackup"
init: false
hassio_api: true
homeassistant_api: true
hassio_role: "admin"
map:
  - backup:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/gordonampotech/autobackup"
ingress: true
host_network: true
